use anyhow::Result;
use std::path::{Path, PathBuf};

pub struct GodotProject {
    pub root: PathBuf,
    pub name: String,
}

impl GodotProject {
    pub fn create(output_dir: &Path, name: &str) -> Result<Self> {
        let root = output_dir.join(name);
        std::fs::create_dir_all(&root)?;

        let project_godot = format!(
            r#"; Engine configuration file.
; Generated by OmniAGP

config_version=5

[application]

config/name="{}"
run/main_scene="res://scenes/main.tscn"
config/features=PackedStringArray("4.3", "GL Compatibility")

[rendering]

renderer/rendering_method="gl_compatibility"
renderer/rendering_method.mobile="gl_compatibility"
"#,
            name
        );

        std::fs::write(root.join("project.godot"), project_godot)?;
        std::fs::create_dir_all(root.join("scenes"))?;
        std::fs::create_dir_all(root.join("scripts"))?;
        std::fs::create_dir_all(root.join("assets/sprites"))?;
        std::fs::create_dir_all(root.join("assets/audio"))?;
        std::fs::create_dir_all(root.join("assets/models"))?;

        Ok(Self {
            root,
            name: name.to_string(),
        })
    }

    pub fn write_script(&self, filename: &str, content: &str) -> Result<()> {
        let path = self.root.join("scripts").join(filename);
        std::fs::write(path, content)?;
        Ok(())
    }

    pub fn write_scene(&self, filename: &str, content: &str) -> Result<()> {
        let path = self.root.join("scenes").join(filename);
        std::fs::write(path, content)?;
        Ok(())
    }
}
